import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { ProductsApi , ApiException, PropertyCreate, PropertyUpdate } from '@thinger-io/thinger-node';
import { Log } from '../lib/log.js';
import {apexChartWidgetSchema} from '../schemas.js';

export function registerDashboardsTools(opts: {
  server: McpServer;
  productsApi: ProductsApi;
}) {
  const { server, productsApi } = opts;
  const thingerUser = process.env.THINGER_USER ?? 'unknown';

  async function isDashBoardPropertyCreated(product: string): Promise<boolean> {
    try {
      await productsApi.readProperty(thingerUser, product, "dashboard");
      Log.log(`Dashboard property exists for user='${thingerUser}' and product='${product}'`);
      return true;
    } catch (err: unknown) {
      Log.log("Dashboard property does NOT exist for user='" + thingerUser + "' and product='" + product);
      return false;
    }
  }

  async function createDashBoardProperty(product: string): Promise<void> {
    const dashboardBase = {
      tabs: [
        {
          name: "Main",
          widgets: []
        }
      ]
    };

    Log.log(`Creating base dashboard property for user='${thingerUser}' and product='${product}'`);
    const property = new PropertyCreate();
    property.property = "dashboard";
    property.name = "dashboard";
    property.value = dashboardBase;

    try {
      const response = await productsApi.createProperty(thingerUser, product, property);
      Log.log(`Successfully created base dashboard property for user='${thingerUser}' product='${product}' response=${JSON.stringify(response)}`);
    } catch (err: unknown) {
      const errorMessage = err instanceof ApiException
        ? `Thinger.io API Error: ${JSON.stringify(err.body, null, 2)?? err.message}`
        : `Unexpected error: ${err instanceof Error ? err.message : String(err)}`;
      Log.error(errorMessage);
      throw err;
    }
  }

  server.registerTool(
    "Add-Thinger-Product-Dashboard-ApexChart-Widget",
    {
      title: "Create or Update Thinger.io Product Specific Property",
      description: [
        "This MCP tool allows you to add ApexChart visualization widgets to Thinger.io product dashboards.",
        "A dashboard is a visual interface that enables real-time and historical monitoring of IoT device data.",
        "Each product can (and should) have its own dashboard to:",
        "- Visualize data from all devices associated with the product",
        "- Monitor aggregated product metrics",
        "- Facilitate trend and pattern analysis",
        "- Provide a consolidated view of product behavior",
        "",
        "## Automatic Dashboard Creation",
        "**IMPORTANT**: This tool automatically checks if the dashboard exists for the specified product.",
        "If it doesn't exist, it creates it automatically before adding the widget. Therefore, you can use this tool",
        "immediately after creating a product without worrying about manually configuring the dashboard.",
        "",
        "## Tool Parameters",
        "",
        "### 1. product (string, required)",
        "Unique identifier of the product in Thinger.io where the widget will be added.",
        "Example: 'temperature_sensors' or 'smart_meters'",
        "",
        "### 2. tab (number, required)",
        "Index (starting from 0) of the dashboard tab where the widget will be added.",
        "- tab: 0 = first tab",
        "- tab: 1 = second tab",
        "- etc.",
        "",
        "### 3. widget (complex object, required)",
        "Object that fully defines the ApexChart widget. Must contain:",
        "",
        "#### 3.1 api (object)",
        "Empty object for API configuration (can be kept as empty object: {})",
        "",
        "#### 3.2 layout (object)",
        "Defines the position and size of the widget in the dashboard grid:",
        "- col (number): Column where the widget starts (e.g., 0, 1, 2...)",
        "- row (number): Row where the widget starts (e.g., 0, 1, 2...)",
        "- sizeX (number): Widget width in grid units (e.g., 6 = half width, 12 = full width)",
        "- sizeY (number): Widget height in grid units (e.g., 4, 6, 8, 15...)",
        "",
        "#### 3.3 panel (object)",
        "Visual configuration of the widget panel:",
        "- color (string): Panel primary color (e.g., '#162756', '#ffffff')",
        "- currentColor (string): Current panel color (typically same as color)",
        "- showFullscreen (boolean): Whether to show fullscreen button (recommended: true)",
        "- showOffline (object): Configuration for showing offline devices",
        "  - type (string): Display type - 'none', 'last_sample', or other values",
        "- subtitle (string): Subtitle text (can be empty: '')",
        "- title (string): Title to display in the widget",
        "- updateTs (number): Update timestamp in milliseconds (use Date.now() or current timestamp)",
        "",
        "#### 3.4 properties (object)",
        "ApexChart-specific properties:",
        "- options (string): JavaScript code string defining ApexCharts configuration",
        "  This is a complete JavaScript code block that defines the chart options.",
        "  IMPORTANT: This must be valid JavaScript code as a string, not a JSON object.",
        "  The code should define a variable 'options' with all ApexCharts settings.",
        "",
        "#### 3.5 sources (array of objects)",
        "Array of data sources for the chart. Each source must include:",
        "",
        "**COMMON FIELDS FOR ALL SOURCE TYPES:**",
        "- source (string): Source type - 'bucket', 'device_bucket', 'device', or 'device_property'",
        "- name (string): Name of the series to display",
        "- color (string): Hex color for the series (e.g., '#2E93fA', '#66DA26', '#ff8800')",
        "- timespan (object): Time range configuration",
        "  - magnitude (string): Time unit - 'minute', 'hour', 'day', 'week', 'month'",
        "  - mode (string): Mode type - 'relative', 'latest', 'configurable', or 'range'",
        "  - period (string): Period type - 'latest' or 'custom'",
        "  - value (number): Number of time units (e.g., 24 for 24 hours)",
        "- $timespan (object): Alternative timespan configuration (with $ prefix)",
        "  Same fields as timespan object",
        "",
        "**TYPE 1: Bucket Source**",
        "For historical data from a data bucket:",
        "```json",
        "{",
        "  \"$timespan\": {",
        "    \"magnitude\": \"day\",",
        "    \"mode\": \"configurable\",",
        "    \"period\": \"latest\",",
        "    \"value\": 1",
        "  },",
        "  \"bucket\": {",
        "    \"backend\": \"mongodb\",  // or 'influxdb', 'dynamodb'",
        "    \"id\": \"em2101_data_bucket\",  // Bucket ID",
        "    \"mapping\": \"voltageL1N\",  // Field to visualize",
        "    \"tags\": {",
        "      \"device\": [],  // Filter by specific devices (empty = all)",
        "      \"group\": []   // Filter by specific groups",
        "    },",
        "    \"user\": \"username\"  // Username who owns the bucket",
        "  },",
        "  \"color\": \"#2E93fA\",",
        "  \"name\": \"Ph1-N\",",
        "  \"source\": \"bucket\",",
        "  \"timespan\": {",
        "    \"magnitude\": \"hour\",",
        "    \"mode\": \"relative\",",
        "    \"period\": \"latest\",",
        "    \"value\": 24",
        "  }",
        "}",
        "```",
        "",
        "**IMPORTANT - Backend-Specific Tags:**",
        "- MongoDB backend: Use 'device' and 'group' tags",
        "- InfluxDB backend: May have custom tags like 'Day', 'Hour', 'Slave', 'tag1', 'tag2'",
        "  Example for InfluxDB:",
        "  ```json",
        "  \"tags\": {",
        "    \"Day\": [],",
        "    \"Hour\": [],",
        "    \"Slave\": [\"GWMD01HFCB4673B517C_1\"],",
        "    \"tag1\": [],",
        "    \"tag2\": []",
        "  }",
        "  ```",
        "",
        "**TYPE 2: Device Bucket Source**",
        "```json",
        "{",
        "  \"aggregation\": {},",
        "  \"color\": \"#4CAF50\",",
        "  \"device_bucket\": {",
        "    \"backend\": \"mongodb\",",
        "    \"device\": \"device_001\",",
        "    \"id\": \"sensor_data\",",
        "    \"mapping\": \"humidity\",",
        "    \"tags\": { \"device\": [], \"group\": [] },",
        "    \"user\": \"username\"",
        "  },",
        "  \"name\": \"Humidity Sensor\",",
        "  \"source\": \"device_bucket\",",
        "  \"timespan\": {",
        "    \"magnitude\": \"hour\",",
        "    \"mode\": \"relative\",",
        "    \"period\": \"latest\",",
        "    \"value\": 12",
        "  }",
        "}",
        "```",
        "",
        "**TYPE 3: Device Resource**",
        "```json",
        "{",
        "  \"color\": \"#2196F3\",",
        "  \"device\": {",
        "    \"id\": \"device_001\",",
        "    \"mapping\": \"value\",",
        "    \"resource\": \"temperature\"",
        "  },",
        "  \"name\": \"Current Temperature\",",
        "  \"source\": \"device\",",
        "  \"timespan\": {",
        "    \"magnitude\": \"minute\",",
        "    \"mode\": \"relative\",",
        "    \"period\": \"latest\",",
        "    \"value\": 60",
        "  }",
        "}",
        "```",
        "",
        "## Complete Usage Examples",
        "",
        "### Example 1: Three-Phase Voltage Monitor (Based on Real Dashboard)",
        "```json",
        "{",
        "  \"product\": \"power_monitors\",",
        "  \"tab\": 0,",
        "  \"widget\": {",
        "    \"api\": {},",
        "    \"layout\": {",
        "      \"col\": 0,",
        "      \"row\": 4,",
        "      \"sizeX\": 9,",
        "      \"sizeY\": 15",
        "    },",
        "    \"panel\": {",
        "      \"color\": \"#162756\",",
        "      \"currentColor\": \"#162756\",",
        "      \"showFullscreen\": true,",
        "      \"showOffline\": {",
        "        \"type\": \"none\"",
        "      },",
        "      \"subtitle\": \"\",",
        "      \"title\": \"VOLTAGE\",",
        "      \"updateTs\": 1730000000000",
        "    },",
        "    \"properties\": {",
        "      \"options\": \"var options = {\\n    series: series,\\nchart: {\\n   background:'#162756',\\n    toolbar: {\\n      show: true,\\n      tools: {\\n        download: true,\\n        selection: true,\\n        zoom: true,\\n        zoomin: true,\\n        zoomout: true,\\n        pan: true,\\n        reset: true\\n      },\\n      autoSelected: 'zoom' \\n    },\\n zoom: {\\n          enabled: true,\\n          type: 'x',  \\n          autoScaleYaxis: true\\n      }\\n},\\n    stroke: {\\n        curve: 'smooth',\\n        width: 1.7\\n    },\\n    grid: {\\n        row: {\\n            colors: ['#233e87', 'transparent'],\\n            opacity: 0.3\\n        }\\n    },\\n    xaxis: {\\n        type: 'datetime',\\n        labels: {\\n            datetimeUTC: false\\n        }\\n    },\\n    yaxis: {\\n        labels: {\\n            formatter: function (val) {\\n                return val.toFixed(2);\\n            }\\n        }\\n    },\\n    tooltip: {\\n        x: {\\n            format: 'dd/MM/yyyy HH:mm:ss'\\n        },\\n        shared: true\\n    },\\n    legend: {\\n        position: 'bottom',\\n        labels: {\\n          colors: '#FFFFFF'\\n        }\\n    }\\n};\"",
        "    },",
        "    \"sources\": [",
        "      {",
        "        \"$timespan\": {",
        "          \"magnitude\": \"day\",",
        "          \"mode\": \"configurable\",",
        "          \"period\": \"latest\",",
        "          \"value\": 1",
        "        },",
        "        \"bucket\": {",
        "          \"backend\": \"mongodb\",",
        "          \"id\": \"em2101_data_bucket\",",
        "          \"mapping\": \"voltageL1N\",",
        "          \"tags\": {",
        "            \"device\": [],",
        "            \"group\": []",
        "          },",
        "          \"user\": \"myusername\"",
        "        },",
        "        \"color\": \"#2E93fA\",",
        "        \"name\": \"Ph1-N\",",
        "        \"source\": \"bucket\",",
        "        \"timespan\": {",
        "          \"magnitude\": \"hour\",",
        "          \"mode\": \"relative\",",
        "          \"period\": \"latest\",",
        "          \"value\": 24",
        "        }",
        "      },",
        "      {",
        "        \"$timespan\": {",
        "          \"magnitude\": \"day\",",
        "          \"mode\": \"configurable\",",
        "          \"period\": \"latest\",",
        "          \"value\": 1",
        "        },",
        "        \"bucket\": {",
        "          \"backend\": \"influxdb\",",
        "          \"id\": \"Dispro_PSP\",",
        "          \"mapping\": \"V2\",",
        "          \"tags\": {",
        "            \"Day\": [],",
        "            \"Hour\": [],",
        "            \"Slave\": [\"GWMD01HFCB4673B517C_1\"],",
        "            \"tag1\": [],",
        "            \"tag2\": []",
        "          },",
        "          \"user\": \"myusername\"",
        "        },",
        "        \"color\": \"#66DA26\",",
        "        \"name\": \"Ph2-N\",",
        "        \"source\": \"bucket\",",
        "        \"timespan\": {",
        "          \"magnitude\": \"hour\",",
        "          \"mode\": \"relative\",",
        "          \"period\": \"latest\",",
        "          \"value\": 24",
        "        }",
        "      },",
        "      {",
        "        \"$timespan\": {",
        "          \"magnitude\": \"day\",",
        "          \"mode\": \"configurable\",",
        "          \"period\": \"latest\",",
        "          \"value\": 1",
        "        },",
        "        \"bucket\": {",
        "          \"backend\": \"influxdb\",",
        "          \"id\": \"Dispro_PSP\",",
        "          \"mapping\": \"V3\",",
        "          \"tags\": {",
        "            \"Day\": [],",
        "            \"Hour\": [],",
        "            \"Slave\": [\"GWMD01HFCB4673B517C_1\"],",
        "            \"tag1\": [],",
        "            \"tag2\": []",
        "          },",
        "          \"user\": \"myusername\"",
        "        },",
        "        \"color\": \"#ff8800\",",
        "        \"name\": \"Ph3-N\",",
        "        \"source\": \"bucket\",",
        "        \"timespan\": {",
        "          \"magnitude\": \"hour\",",
        "          \"mode\": \"relative\",",
        "          \"period\": \"latest\",",
        "          \"value\": 24",
        "        }",
        "      }",
        "    ],",
        "    \"type\": \"apex_charts\"",
        "  }",
        "}",
        "```",
        "",
        "### Example 2: Simple Temperature Chart",
        "```json",
        "{",
        "  \"product\": \"temperature_sensors\",",
        "  \"tab\": 0,",
        "  \"widget\": {",
        "    \"api\": {},",
        "    \"layout\": {",
        "      \"col\": 0,",
        "      \"row\": 0,",
        "      \"sizeX\": 12,",
        "      \"sizeY\": 8",
        "    },",
        "    \"panel\": {",
        "      \"color\": \"#1976D2\",",
        "      \"currentColor\": \"#1976D2\",",
        "      \"showFullscreen\": true,",
        "      \"showOffline\": {",
        "        \"type\": \"last_sample\"",
        "      },",
        "      \"subtitle\": \"Last 24 Hours\",",
        "      \"title\": \"Temperature Monitoring\",",
        "      \"updateTs\": 1730000000000",
        "    },",
        "    \"properties\": {",
        "      \"options\": \"var options = {\\n    series: series,\\n    chart: {\\n        background: '#1976D2',\\n        toolbar: { show: true, autoSelected: 'zoom' },\\n        zoom: { enabled: true, type: 'x', autoScaleYaxis: true }\\n    },\\n    stroke: { curve: 'smooth', width: 2 },\\n    xaxis: { type: 'datetime', labels: { datetimeUTC: false } },\\n    yaxis: {\\n        labels: { formatter: function(val) { return val.toFixed(1) + '°C'; } }\\n    },\\n    tooltip: {\\n        x: { format: 'dd/MM/yyyy HH:mm' },\\n        shared: true\\n    },\\n    legend: { position: 'bottom', labels: { colors: '#FFFFFF' } }\\n};\"",
        "    },",
        "    \"sources\": [",
        "      {",
        "        \"$timespan\": {",
        "          \"magnitude\": \"day\",",
        "          \"mode\": \"configurable\",",
        "          \"period\": \"latest\",",
        "          \"value\": 1",
        "        },",
        "        \"bucket\": {",
        "          \"backend\": \"mongodb\",",
        "          \"id\": \"temperature_bucket\",",
        "          \"mapping\": \"temp\",",
        "          \"tags\": {",
        "            \"device\": [],",
        "            \"group\": []",
        "          },",
        "          \"user\": \"myusername\"",
        "        },",
        "        \"color\": \"#FF5722\",",
        "        \"name\": \"Temperature\",",
        "        \"source\": \"bucket\",",
        "        \"timespan\": {",
        "          \"magnitude\": \"hour\",",
        "          \"mode\": \"relative\",",
        "          \"period\": \"latest\",",
        "          \"value\": 24",
        "        }",
        "      }",
        "    ],",
        "    \"type\": \"apex_charts\"",
        "  }",
        "}",
        "```",
        "",
        "### Example 3: Real-Time Device Resource",
        "```json",
        "{",
        "  \"product\": \"smart_meters\",",
        "  \"tab\": 0,",
        "  \"widget\": {",
        "    \"api\": {},",
        "    \"layout\": {",
        "      \"col\": 0,",
        "      \"row\": 0,",
        "      \"sizeX\": 6,",
        "      \"sizeY\": 6",
        "    },",
        "    \"panel\": {",
        "      \"color\": \"#424242\",",
        "      \"currentColor\": \"#424242\",",
        "      \"showFullscreen\": true,",
        "      \"showOffline\": {",
        "        \"type\": \"none\"",
        "      },",
        "      \"subtitle\": \"Real-time monitoring\",",
        "      \"title\": \"Power Consumption\",",
        "      \"updateTs\": 1730000000000",
        "    },",
        "    \"properties\": {",
        "      \"options\": \"var options = {\\n    series: series,\\n    chart: {\\n        type: 'area',\\n        background: '#424242',\\n        toolbar: { show: true }\\n    },\\n    stroke: { curve: 'smooth', width: 2 },\\n    fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.7, opacityTo: 0.3 } },\\n    xaxis: { type: 'datetime' },\\n    yaxis: { labels: { formatter: function(val) { return val.toFixed(2) + ' kW'; } } },\\n    tooltip: { x: { format: 'HH:mm:ss' } },\\n    legend: { position: 'top', labels: { colors: '#FFFFFF' } }\\n};\"",
        "    },",
        "    \"sources\": [",
        "      {",
        "        \"color\": \"#FFC107\",",
        "        \"device\": {",
        "          \"id\": \"meter_001\",",
        "          \"mapping\": \"power\",",
        "          \"resource\": \"power_consumption\"",
        "        },",
        "        \"name\": \"Power (kW)\",",
        "        \"source\": \"device\",",
        "        \"timespan\": {",
        "          \"magnitude\": \"minute\",",
        "          \"mode\": \"relative\",",
        "          \"period\": \"latest\",",
        "          \"value\": 30",
        "        }",
        "      }",
        "    ],",
        "    \"type\": \"apex_charts\"",
        "  }",
        "}",
        "```",
        "",
        "## Important Notes",
        "",
        "1. **Colors**: Use hexadecimal color codes (#RRGGBB)",
        "2. **Options**: The 'options' field must be a JavaScript code string, not a JSON object",
        "   - Escape newlines as \\n",
        "   - Escape quotes as \\'",
        "   - Must define a variable named 'options'",
        "   - Can reference 'series' variable which is automatically provided",
        "3. **Timestamps**: Use current timestamp in milliseconds for updateTs (Date.now())",
        "4. **Backend Types**: 'mongodb', 'influxdb', or 'dynamodb'",
        "5. **Tags**: Structure varies by backend - check your bucket configuration",
        "6. **Timespan**: Include both 'timespan' and '$timespan' objects",
        "7. **Layout**: Grid system typically has 12 columns width",
        "8. **User Field**: Include the username who owns the bucket/device",
        "9. **Automatic Dashboard**: The tool creates the dashboard if it doesn't exist",
        "",
        "## Best Practices",
        "",
        "- Create a dashboard immediately after creating a product",
        "- Use distinct colors for each data series",
        "- Adjust widget size based on data importance",
        "- Set showFullscreen to true for better user experience",
        "- Use descriptive titles that clearly indicate the data being displayed",
        "- Match timespan configurations between $timespan and timespan objects",
        "- Consider the background color when choosing text/series colors for readability",
        "- Use appropriate chart types in options (line, area, bar, etc.) based on data nature"
      ].join("\n"),
      inputSchema: {
        product: z.string().min(1).describe("ID of the Product Property Tool"),
        tab: z.number().min(0).describe("Index of the dashboard tab to add the widget to"),
        widget: apexChartWidgetSchema
      }
    },
    async ({ product, tab, widget } ) => {
      try {
        if (! await isDashBoardPropertyCreated(product)) {
          await createDashBoardProperty(product);
        }

        Log.log(`Adding ApexChart widget to dashboard of product='${product}'`);
        const dashboardProperty = await productsApi.readProperty(thingerUser, product, "dashboard");
        const dashboard = dashboardProperty.value;
        dashboard.tabs[tab].widgets.push(widget);

        // Update the dashboard property with the new widget
        const propertyUpdate = new PropertyUpdate();
        propertyUpdate.name = "dashboard";
        propertyUpdate.property = "dashboard";
        propertyUpdate.value = dashboard;
        const response = await productsApi.updateProperty(thingerUser, product, "dashboard", propertyUpdate);
        Log.log(`Successfully created dashboard widget in product='${product}'`);

        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(response, null, 2),
            }
          ],
        }
      } catch (err: unknown) {
        const errorMessage = err instanceof ApiException
          ? `Thinger.io API Error: ${err.body ?? err.message}`
          : `Unexpected error: ${err instanceof Error ? err.message : String(err)}`;
        Log.error(errorMessage);
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: errorMessage,
            },
          ],
        };
      }
    }
  );
}
